import type { Metadata } from "next";
import "./globals.css";
import MainLayout from "./layouts/MainLayout";
import { MainProvider } from "@/context/MainContext";

export const metadata: Metadata = {
  title: "Wellmedia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MainLayout>
          <MainProvider>{children}</MainProvider>
        </MainLayout>
      </body>
    </html>
  );
}
